[programs.devnet]
anchor_escrow = "BxNK559xJFcDD1s7qWJHpQeVg8ZrySXBZHCbLYZFqAnb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/y1zYW-ovVofq7OzZo0Z6IHenRnyq_Pbd"
wallet = "~/new-keypair2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.29.0" # `anchor-cli` version to use
solana_version = "1.17.0" # Solana version to use
