[features]
resolution = true
skip-lint = false
seed = true


[programs.devnet]
anchor_airdrop_escrow = "2TS27Nwkkj5xnWxvBYCpjTmxxg8He51L54VbY9fM6yoS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/new-keypair2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://solana-devnet.g.alchemy.com/v2/y1zYW-ovVofq7OzZo0Z6IHenRnyq_Pbd"
ledger = ".anchor/test-ledger"
rpc_port = 8899
